### ISSUE TITLE
I have this issue in project. what should i do please tell i am stuck in this problem

### ISSUE THREAD

**Issue by FazalRehman1919** [webpack-contrib/sass-loader#1109]
ERROR in ./src/StripNavbarProject/Main.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/StripNavbarProject/Main.css) 5:36-81

Module not found: Error: Can't resolve './images/hero.svg' in 'E:\Youtube-ReactJs\FreeCodeCamp\freecodecamp13-15\src\StripNavbarProject'

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Anyway, based on your error, you don't have image by this path, check it, don't forget sass resolve assets based on entry file, i.e. all nested `@use`/`@import` should have path to assets from entry point, feel free to feedback

**Comment by FazalRehman1919** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> Anyway, based on your error, you don't have image by this path, check it, don't forget sass resolve assets based on entry file, i.e. all nested `@use`/`@import` should have path to assets from entry point file, feel free to feedback

Thank you of your reply brother but the main issue is that, that i use external css file for my project and when i connect this css file in project than this issue rise but when i disconnect the css file than everything work fine but you know css is necessary.

**Comment by alexander-akait** [comment]
@FazalRehman1919 What do you use? You can rewrite path in `url(...)`, some popular projects, like bootstrap/etc have an option for such cases
