### ISSUE TITLE
Sass loader v16 compile issue with resolve-url-loader

### ISSUE THREAD

**Issue by mmarton** [webpack-contrib/sass-loader#1225]
### Actual Behavior

Hi!

I have a strange issue when upgrading to sass-loader v16. (I know there is a bc break with the config, but I don't have any config and expected flawless upgrade)

My  project has a couple 1000 line scss, everything works fine with v16, and without using the legacy api option, except the import of 1 specific font.

I've created a small reproducer at https://github.com/mmarton/sass-loader-poc

### Expected Behavior

```
ERROR in ./main.scss
Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  expected "base" to be absolute path to a valid directory, got "data:;charset=utf-8,/*%20gloria-hallelujah-latin-400-normal...
```

### How Do We Reproduce?

follow the readme at my repo: https://github.com/mmarton/sass-loader-poc

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```

  System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.87 GB / 15.47 GB
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.88
  Packages:
    css-loader: ^7.1.2 => 7.1.2 
    resolve-url-loader: ^5.0.0 => 5.0.0 
    sass-loader: ^16.0.0 => 16.0.0 
    webpack: ^5.93.0 => 5.93.0 
    webpack-cli: ^5.1.4 => 5.1.4 
```

**Comment by alexander-akait** [comment]
Please open an issue in `resolve-url-loader`, looks like they don't have `data:` Data URI in source maps

Also I want to say - I think you don't need `resolve-url-loader` at all, most of libraries allow to set path to assets using variables, better to use it, because parsing source maps and using postcss to change them is very slow

Feel free to feedback

**Comment by alexander-akait** [comment]
As workaround you can use `api: "legacy"`

**Comment by mmarton** [comment]
Hmmm, I've dig deeper, and fount out that if I specify the path fully then it works without the legacy settings.

doing this in my main.scss (which is the lib's main setting anyway):
```diff
-@import '~@fontsource/gloria-hallelujah';
+@import '~@fontsource/gloria-hallelujah/index.css';
```

This way it compiles without any issue. I have no idea why, but it feels like some BC thing here and not on resolve-url-loader's side.

**Comment by alexander-akait** [comment]
Weird, it should work without it, can you create a small reproducible repo, maybe bug on `sass` side, so we need to report about

**Comment by mmarton** [comment]
I've updated the one I've linked in my first comment
Check the readme and main.scss

https://github.com/mmarton/sass-loader-poc

**Comment by nex3** [comment]
The reason `@import '~@fontsource/gloria-hallelujah/index.css'` works fine is that it's not being processed by Sass at all. `@import` rules whose URLs end in `.css` are interpreted by Sass as [plain-CSS `@import`s](https://sass-lang.com/documentation/at-rules/import/#plain-css-imports), so something else must be handling _that_ at a later stage.

The `data:` URL appearing here is the documented behavior of [`ImporterResult.sourceMapUrl`](https://sass-lang.com/documentation/js-api/interfaces/importerresult/#sourceMapUrl):

> If [the source map URL] isn't set, it defaults to a `data:` URL that contains the contents of the loaded stylesheet.

The expectation is that a full-on [`Importer`](https://sass-lang.com/documentation/js-api/interfaces/importer/) wants full control over what every URL means, including making it possible for `file:` URLs *not* to refer to the literal filesystem. If you want a simpler importer interface that handles filesystem stuff like this automatically, a [`FileImporter`](https://sass-lang.com/documentation/js-api/interfaces/fileimporter/) may be a better fit. (It's also a bit more efficient in the embedded host, since it doesn't need to make separate requests for loads or relative canonicalization.)

I've verified locally that adding `sourceMapUrl: canonicalUrl` [here](https://github.com/webpack-contrib/sass-loader/blob/c1997de00aaa922b86cb33a62b40cf9c055e0d2d/src/utils.js#L694) fixes this bug.
