### ISSUE TITLE
When using soureMaps application bundle file size increases

### ISSUE THREAD

**Issue by ghost** [webpack-contrib/sass-loader#185]
```
{
        test: /\.scss$/,
        loader: "style-loader/useable!css-loader?sourceMap!sass-loader?sourceMap"
}
```

With above configuration sourceMap works just fine, tested for HMR. 

But I noticed bundle files generated (not source map) are larger than bundle files generated without sourceMap like below. (40 to 50 percent larger, 500 KB becomes 900 KB)

```
{
        test: /\.scss$/,
        loader: "style-loader/useable!css-loader!sass-loader"
}
```

I am not sure what are we getting into the bundle files. Ideally source maps generated should be kept in the .map files generated. If you are not able to re-produce this, I will spend some time on setting up a repo reproducing this problem.

**Comment by Phoenixmatrix** [comment]
What is your devtool setting?

**Comment by vishwanath-to** [comment]
Tried with 'source-map' and 'cheap-module-source-map' which supposedly mentioned as production ready at http://webpack.github.io/docs/configuration.html#devtool

**Comment by Phoenixmatrix** [comment]
Interesting. I would have expected it from inline-source-map (since the sourcemap is part of the output).

Note that when they say "production ready", what they mean is "can be used to debug minified code in production".

**Comment by jhnns** [comment]
> But I noticed bundle files generated (not source map) are larger than bundle files generated without sourceMap like below. (40 to 50 percent larger, 500 KB becomes 900 KB)

That is correct, because the source map contains the original source code (stored in the `contents` property). This is because then you don't need to map source map paths to your file system in your developer tools. They just work.

If you do not want to include the original source code (e.g. because you want to use source maps in production), you should disable the [`sourceMapContents`](https://github.com/sass/node-sass#sourcemapcontents)-flag. In this case, the source map will only contain mapping information.

We should probably mention that in the README, though...

**Comment by evilebottnawi** [comment]
I think it is expected behavior and no need to be documented. Feel free to feedback.
