### ISSUE TITLE
Incremental builds

### ISSUE THREAD

**Issue by strarsis** [webpack-contrib/sass-loader#198]
Does this loader support or even webpack as whole incremental builds?
Where only changed/new files are processed, the rest just taken from cache?

**Comment by Phoenixmatrix** [comment]
It does, in a way. if you require('./foo') and require('./bar') where foo and bar are scss files, and you change foo, it will only recompile foo, not bar.

Where it doesn't (and can't really because of how node-sass works) is if bar @import baz, and you change baz, it will recompile bar (and everything bar imports).

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/sass-loader/issues/296. 

Closing this out, please feel free to reopen if your think what issue don't related to issue above. Thanks!
