### ISSUE TITLE
Using sass-loader with webpack 1.x

### ISSUE THREAD

**Issue by viksit** [webpack-contrib/sass-loader#415]
Is it possible to use webpack 1.x with some version of sass-loader? Are there any examples of doing that?

**Comment by jhnns** [comment]
You should be able to use the sass-loader 4.x with webpack 1. We dropped official support with sass-loader 5.x which means that it *might* work, but there is no guarantee. [This is the sass-loader 4.x documentation](https://github.com/webpack-contrib/sass-loader/tree/archive/webpack-1).

I recommend switching to webpack 2 as soon as possible since we don't have the manpower to maintain multiple versions. Additionally, I think the transition from webpack 1 to webpack 2 isn't as hard as it may seem. There were little breaking changes. Everything you need to know is documented in the [migration guide](https://webpack.js.org/guides/migrating/).
