### ISSUE TITLE
dart-sass?

### ISSUE THREAD

**Issue by jethrolarson** [webpack-contrib/sass-loader#435]
Is there any intent to swap to using https://github.com/sass/dart-sass when it goes gold?

Supposedly it's way faster, and speed hasn't been one of sass's strong points.

**Comment by evilebottnawi** [comment]
@jethrolarson 'dart-sass' is cool project, but there are a lot of bugs with `sass` original compatibility :sob:

**Comment by michael-ciniawsky** [comment]
Agreeing with @evilebottnawi here, `dart-sass` is still under 'heavy' development and doesn't cover the whole SASS spec yet

**Comment by lukepolo** [comment]
Just went into beta , may be with looking into now

**Comment by evilebottnawi** [comment]
@lukepolo seems more related to `node-sass`, we should have `dart-sass` port on nodejs. Now we don't have this port and it is impossible.

**Comment by graingert** [comment]
@evilebottnawi you can do [`npm install sass`](https://www.npmjs.com/package/sass) https://github.com/sass/dart-sass#from-npm

**Comment by evilebottnawi** [comment]
@graingert can you explain why `dart-sass` is better (or not) than `node-sass`? Faster, better compatibility with orgiinal sass implementation or other feature. But main problem is `dart-sass` don't support custom importer, without this feature, it is impossibly to implement support `dart-sass` in `sass-loader`.

**Comment by graingert** [comment]
@evilebottnawi saves waiting for the compile step on npm install

Also it's the future of sass: http://sass.logdown.com/posts/1022316-announcing-dart-sass

**Comment by nex3** [comment]
@evilebottnawi Importer support is a high-priority feature for us; we consider it blocking a 1.0.0 stable release.

**Comment by rayfoss** [comment]
For those googling around on how to use dart-sass instead of libsass/SassC in Vue, the answer is you can't. Until it has webpack/vue-loader/sass-loader support. Which can't happen without importer support, even if you are willing to simplify your sass to work with dart-sass.

You can follow progress here https://github.com/sass/dart-sass/issues/12

**Comment by nex3** [comment]
I just put out https://github.com/sass/dart-sass/pull/186 which adds support for synchronous importers. I hope to land it tomorrow. Asynchronous importers will probably take more work, but this is an important step.

**Comment by graingert** [comment]
Looks like @nex3 has merged async import support, can you reopen this ticket @michael-ciniawsky?

**Comment by nex3** [comment]
I'm planning to release a beta release with async importer support later this week. If possible, this should pass the `fibers` package to `render()` if it's using the asynchronous `render()` function; otherwise, it will run substantially slower than `renderSync()`. See [the README](https://github.com/sass/dart-sass/blob/master/README.md#javascript-api) for details.

**Comment by reinerBa** [comment]
For me it would be greate if the `sass-loader` would support the usage ´sass´ compiler because `node-sass` forces me to install `node-gyp` which is sometimes a big problem :( as Golo describes here in a [node-sass issue](https://github.com/sass/node-sass/issues/2133)

**Comment by evilebottnawi** [comment]
Should be done after https://github.com/webpack-contrib/sass-loader/pull/533

**Comment by 44LD** [comment]
@jethrolarson @evilebottnawi 
Some posts about ruby-sass. Now it's actual
http://sass.logdown.com/posts/7081811

**Comment by nex3** [comment]
Now that #533 has landed, what are the next steps here?

**Comment by jhnns** [comment]
Wow ruby-sass was deprecated? Didn't see that coming 😁

Are you planing with [dart-sass](https://www.npmjs.com/package/dart-sass) to expose the same API as node-sass? What notable differences are there between dart-sass and node-sass?

Regarding your suggestions:

From a conceptual perspective, I prefer the former one with `require()` because it pushes the dependency explicitly to the user. But since we already need to apply some fixes for node-sass (e.g. [the async job queue](https://github.com/webpack-contrib/sass-loader/blob/9409e1717bc19de930c02138ddcc011168eaaada/lib/loader.js#L42)), I think it's better to have the latter in place. This way, we can apply fixes and adjustments as necessary. 

> What do we do about imports that load CSS files as SCSS?

We should remove that feature with a breaking change since it's deprecated anyway. Until then, I can add the same deprecation warning as in https://github.com/sass/libsass/pull/2613. 

---

If dart-sass is mature enough and reliable, I'm open to switch to dart-sass as the new default. I suspect the node-sass' thread pool issue (https://github.com/sass/node-sass/issues/857) to be responsible for the performance problems at sass-loader #296 since we're using the custom importer feature.

**Comment by nex3** [comment]
> Are you planing with dart-sass to expose the same API as node-sass?

Yep!

> What notable differences are there between dart-sass and node-sass?

Dart Sass doesn't support sourcemaps yet; see https://github.com/sass/dart-sass/issues/2. It also doesn't support the `precision` or `sourceComments` options. Otherwise the API should be identical.

> If dart-sass is mature enough and reliable, I'm open to switch to dart-sass as the new default. I suspect the node-sass' thread pool issue (sass/node-sass#857) to be responsible for the performance problems at sass-loader #296 since we're using the custom importer feature.

It's officially in stable releases, but that hasn't been true for very long yet. It's up to you whether you want to make it the default now or not.

**Comment by xzyfer** [comment]
>What do we do about imports that load CSS files as SCSS?

CSS imports are being deprecated in node-sass@4.9.0 (imminent) and, removed in node-sass@5 (late april-may)

**Comment by nex3** [comment]
@jhnns I'd be happy to pitch in a PR for this. Would you prefer to require users to explicitly specify a Sass implementation, or to default to Dart Sass? We could also default to Node Sass, but since that's harder to install it seems less ideal to have as a dependency.

**Comment by graingert** [comment]
Could just not depend on sass at all and take it as a parameter

**Comment by philippkuehn** [comment]
+1 for dropping node-sass and explicitly specify sass implementation

**Comment by evilebottnawi** [comment]
@philippkuehn we can't drop `node-sass`

**Comment by just-boris** [comment]
I thought, that the change would be a major version bump for `sass-loader`. Why not to drop `node-sass` then?

**Comment by evilebottnawi** [comment]
@just-boris legacy support projects. we move `node-sass` to `peerDependencies` to allow using this loader with `node-sass` and `dart-sass`. Just add check on `dart-sass` here https://github.com/webpack-contrib/sass-loader/blob/master/lib/loader.js#L27 and improve tests. And we will support `node-sass` and `dart-sass`. PR welcome

**Comment by just-boris** [comment]
If there will be both `dart-sass` and `node-sass` in peer-dependencies, one of them will be always a missing.

Npm will produce a warning about that, but I do not expect any warnings when I do everything right.

**Comment by graingert** [comment]
I'd rather see sass-loader (for dart-sass) and sass-loader-node-sass

**Comment by evilebottnawi** [comment]
@just-boris i was misleading, **we remove `node-sass`** from `peer` to allow choose `node-sass` or `dart-sass` for loader.

@graingert no new loader, because no one will maintain him, say simply than do

**Comment by graingert** [comment]
It would be with lerna, there would be three projects, including
sass-loader-core. sass-loader would be a thin wrapper that passed (and has
a peerDep of) dart-sass to sass-loader-core sass-loader-node-sass would be
a thin wrapper that passed (and has a peerDep of node-sass) to
sass-loader-core.

**Comment by evilebottnawi** [comment]
@graingert do you have time on this?

**Comment by graingert** [comment]
I can set this all up, if that's the structure that you want

**Comment by xzyfer** [comment]
Fwiw gulp-dart-sass has recently popped to serve that community.

**Comment by evilebottnawi** [comment]
Anyway PR welcome to integrate `dart-sass`, it is should be not difficult.

**Comment by xzyfer** [comment]
We've also added Dart Sass to the unofficial benchmark the Node Sass team
keeps an eye on - https://github.com/postcss/benchmark

**Comment by graingert** [comment]
It should include the `npm install` time

**Comment by xzyfer** [comment]
Sure if you're running an install _every_ time you compile your Sass code in Dec.

**Comment by graingert** [comment]
It ends up happening a lot, eg when building docker images using Dockerfile

**Comment by evilebottnawi** [comment]
@graingert you can prepare docker image before run some stuff

**Comment by graingert** [comment]
@evilebottnawi I know that, I used to maintain shipwright a tool for doing just that, but sometimes it's fiddly

**Comment by nex3** [comment]
> Could you actually use the real dart version as a backend instead of a to-javascript-transpiled one?

Integrating the Dart VM version into a package like this which supports the Node Sass API would be fairly difficult. When you're running a subprocess, it's much harder to define importers or custom functions, because they have such a fine-grained mode of communication. sass/dart-sass#248 discusses the possibility of defining a protocol that could be used over stdin/stdout to make this work, but at the moment we don't have anyone signed up to implement the JS side of that protocol.

If you're willing to abandon importer/custom function support, it would be a lot easier to wrap the Dart executable. This is essentially how the [`grunt-contrib-sass`](https://www.npmjs.com/package/grunt-contrib-sass) package works with Ruby Sass. But that's not a sacrifice everyone would be willing to make.

**Comment by rayfoss** [comment]
>  But that's not a sacrifice everyone would be willing to make.

We are already making a lot of painful sacrifices to use sass with node-sass. Sharing `node_modeles` with docker, faster compilation, never break my installation after a node/system update, just to name a few... node-sass is a pita, dart-sass can't possibly be worse.

To be fair, I get it won't be easy to make the switch, it'll inevitably have to be a breaking switch, perhaps an installation option to make it easier, similar to how less support is set up?

**Comment by xzyfer** [comment]
Fwiw node-sass installation issues will be a thing of the past before too
long

**Comment by graingert** [comment]
N-API and or wasm I believe

**Comment by just-boris** [comment]
I have switched to the modified version of this loader (from https://github.com/webpack-contrib/sass-loader/pull/573) and dart-sass for a fairly big project (10k lines of SCSS) and did not any significant notice performance slow down. It could be slower, but with watch mode and incremental builds, it doesn't actually matter.

On other hand, it simplifies infrastructure a lot, when you have to deal only with pure Javascript dependencies.

**Comment by samayo** [comment]
What is the status of this issue? Can we use now dart-sass in webpack? I can't see any documentation to for the webpack config

**Comment by Simek** [comment]
@samayo Official NPM package `sass` has been switched to Dart implementation a while ago (https://www.npmjs.com/package/sass) so you do not need to use/change to `dart-sass` (it's a mirror).

**Comment by samayo** [comment]
@Simek Thanks, I do have sass and sass-loader
```json
"devDependencies": {
  "sass": "^1.23.0",
  "sass-loader": "^8.0.0"
```
and I have the loaders setup correctly

```js
{
 test: /\.s[ac]ss$/i,
  use: [
   'style-loader',
   'css-loader',
   {
   loader: 'sass-loader',
    options: {
     implementation: require('sass'),
    },
   },
  ],
}
```
The config is as suggested in https://github.com/webpack-contrib/sass-loader#implementation

But I can't seem to use the sass module features as mentioned in https://sass-lang.com/documentation/at-rules/use

If npm/sass is just fetching dart-sass, these options should be available, i think.

**Comment by Simek** [comment]
@samayo Check out this issue: https://github.com/webpack-contrib/sass-loader/issues/766. It seem that it's quite a new feature and it's not fully supported yet. 

Tests has been added just few days ago:
https://github.com/webpack-contrib/sass-loader/commit/185ba80d1bde2a44a8e60069eca0c7e266531037

**Comment by samayo** [comment]
@Simek  Thanks. I still can't verify if this feature is added or not from reading the commit. It seems like the readme is updated, tests written but feature isn't there yet? I will ask on dart-sass if they can make something of it, but thanks ... at least now i'm half certain i'm not going mad :)

**Comment by evilebottnawi** [comment]
We officially support dart-sass with `@use` what is problem? Check you use `sass` and dart-sass and use latest version of loader

**Comment by stratboy** [comment]
Currenly experiencing the same problem: latest sass-loader doesn't fully recognize current scss syntax. Using:

```
    "sass": "^1.49.7",
    "sass-loader": "^12.6.0",
     "webpack": "^5.69.0",
```
