### ISSUE TITLE
Can sass-loader keep variables name as comments?

### ISSUE THREAD

**Issue by aleen42** [webpack-contrib/sass-loader#506]
Recently, I have met a use case when I need to load user configuration like theme color at runtime, and parse it to change CSS files, which is compiled by sass-loader. Is there any suggestion about how to implement it in a clever way? In my opinion, I have tried to work around this by keep variables name in comments when parsing by the loader, and replace them at runtime by creating a style to override.

**Comment by aleen42** [comment]
I have found a solution through using CSS custom properties, and any better ideas for a better compatibilites?

**Comment by michael-ciniawsky** [comment]
Not directly for SASS, but you could consider using `postcss-custom-properties` and enhance the PostCSS AST with the variables as long as browser support for CSS Custom Properties isn't mature enough. The plugin has a `fallback` option doing exactly what you're tying to achieve via a mixin atm. Otherwise your approach such work just fine since it's nearly using the same logic. Closing as there is nothing we can do to fix this in the scope of `sass-loader` itself

**Comment by aleen42** [comment]
@michael-ciniawsky Thanks for your suggestion, and I have worked around this by dynamically inject style at runtime with JavaScript, which can solve the compatibility problem:

```js
/** set custom properties for CSS */
var customCSSStyleText = '';
var customSkins = settings.skins;
for (var i = 0; i < document.styleSheets.length; i++) {
    var stylesheet = document.styleSheets[i];
    var rules = stylesheet.cssRules ? stylesheet.cssRules : stylesheet.rules;
    for (var j = 0; j < rules.length; j++) {
        /var\(.*?\)/gi.test(rules[j].cssText) && (
            customCSSStyleText += rules[j].cssText.replace(/var\((.*?), (.*?)\)/gi, function ($0, $1, $2) {
                return customSkins && customSkins[$1] ? customSkins[$1] : $2;
            })
        );
    }
}

customCSSStyleText && document.body.appendChild('<style>' + customCSSStyleText + '</style>');
```
