### ISSUE TITLE
Export decoupled Sass importer

### ISSUE THREAD

**Issue by vvanpo** [webpack-contrib/sass-loader#873]
> Importer for webpack only for webpack and it is out of scope support other tools. You can create own impoter based on our logic. Thanks

_Originally posted by @evilebottnawi in https://github.com/webpack-contrib/sass-loader/issues/676#issuecomment-480862910_

Would it still be out of scope if some of those other tools are specifically trying to mimic how `sass-loader` works? For example, it's common to use Jest to unit test source files that are otherwise bundled by Webpack. We can use Jest's `moduleNameMapper` configuration to mimic each Webpack alias. But when it comes to compiling Sass, we need to define a transformer that works identically to `sass-loader`, or else all Sass imports in Jest will fail.

One common example of this is Vue.js single-file components, where `vue-jest` runs `.vue` files through a compiler that also calls `sass`. But while we've tried to define an importer that mimics how `sass-loader` works, supporting both aliases and bare imports to `node_modules`, we're finding it an uphill battle: https://github.com/vuejs/vue-jest/pull/256#issuecomment-664764912. All of these intricacies have already been worked out in `sass-loader`, so it only makes sense to try and use its implementation if at all possible.

Another use case I've come across is in codebases that run both Webpack and Rollup over the same source files. This might sound unusual but sometimes happens in monorepos where one subpackage exports a component library using Rollup, and another package consumes the source files of that component library in an application built by Webpack. The official Vue.js Rollup plugin doesn't have any built-in Sass importer, for example, so users often expect to be able to use `sass-loader`'s `~` syntax to import from `node_modules`, and are confused when it doesn't work: https://github.com/vuejs/rollup-plugin-vue/issues/300#issuecomment-646965142

If you're open to the idea of exporting a `/dist/importer.js` file defining the Sass importer used by `sass-loader` (but with the loader API-specific pieces extracted out, if that's even possible), I'm happy to attempt a PR. If you're not open to the idea, that's okay, I'll likely just try to copy much of the implementation in `src/utils.js` and reuse it directly in `vue-jest`, although I would of course prefer not to duplicate all that code.

**Comment by evilebottnawi** [comment]
Sounds very crazy, but I am ready to discuss it. Here some problems:
- `importer.js` will not work without webpack resolver, there are a lot of stuff under the hood, like `~`, PnP, Server-relative URLs, absolute paths on linux/windows, `exports` (rollup refused to support this), it will be very hard to implement without webpack resolver, but you can use `enhanced-resolve`
- we often have to correct the algorithm (because sass architecture for importers is not very good and sometimes they change it in patch version), so if we export this we need to do breaking change on each change, it is not good

In fact, this may require dragging not a small part of the webpack under the hood. If this is acceptable to you - good. But I want to avoid using semver for this. I've spent enough time to explore `sass` resolving algorithm, so the chances of some changes are minimal, or they will be really just fixes.

It’s very strange, until recently, developers from rollup team said how bad we are and how terrible everything we have, but now we have request on exporting abilities :taco:  

One more question. What about `less-loader`/`stylus-loader`/etc?

**Comment by vvanpo** [comment]
I'm not on the Rollup team (or any team for that matter, I'm just contributing to tools I make use of), but I find it interesting they don't want to support `exports`; I imagine they'll be forced to reverse that decision once native ESM sees widespread adoption.

You bring up a lot of interesting details I hadn't considered, although it sounds like `enhanced-resolve` takes care of them all, thanks for pointing me to that. I'm not all that familiar with the loader API (I've only ever written one very simple loader), so it's difficult for me to picture all the complexities of this, but hopefully I'll gain a better understanding once I actually try it. I'll do my best to come up with a proof-of-concept this week.

That's unfortunate to hear that Sass' importer API has seen a lot of breaking changes. I see now that `dart-sass`' documentation for the API just links to `node-sass`' docs, which themselves consider the API to be experimental. That's too bad considering how heavily it is relied upon everywhere. Not following semver for this potential importer sounds very reasonable, then.

I don't know about Less or Stylus, I've only ever used Sass so they're not really on my radar. Vue.js' `vue-loader` supports both, but so far `vue-jest` only support Sass and Stylus, and for Stylus it makes no attempts to mimic Webpack resolution. There is at least one bug open for this, so it sounds like we'll want to do something similar for Stylus in the future too.

**Comment by evilebottnawi** [comment]
Done in master, release will be soon
