### ISSUE TITLE
Modernise fibers recommendation

### ISSUE THREAD

**Issue by robinwhittleton** [webpack-contrib/sass-loader#918]
(this is a combo docs / functionality request)

### Expected Behavior / Situation

`sass-loader` uses modern async approaches.

### Actual Behavior / Situation

`sass-loader` recommends using `fibers`, a package that was deprecated last year: https://github.com/laverdet/node-fibers#readme . The author has said that they’ll continue to support the package for as long as possible, but the literal writing is on the wall.

### Modification Proposal

Is there a plan for a `sass-loader` future where `fibers` isn’t needed to get an equiavalent speed boost?

**Comment by alexander-akait** [comment]
> sass-loader uses modern async approaches.

I think better ask this here https://github.com/sass/dart-sass#javascript-api, we need async resolver (i.e. `importer`) so we can't use `sync` API, for async it is recommendation to use `fibers`, I think better ask `sass`/`dart-sass`/`node-sass` team why `renderSync` is faster then async `render`, because in most cases async API is faster

**Comment by robinwhittleton** [comment]
Thanks for the hint! This will be addressed in https://github.com/sass/dart-sass/issues/868 when it’s addressed.
