### ISSUE TITLE
fibers and node 16

### ISSUE THREAD

**Issue by rrd108** [webpack-contrib/sass-loader#939]
The fibers package does not support node 16.

I had to downgrade to make my apps run. Any plan to handle this?

**Comment by alexander-akait** [comment]
How we can handle this?

**Comment by alexander-akait** [comment]
Don't use fibars it should not bad for perf now

**Comment by rrd108** [comment]
Well. I am new to node. Can I use sass-loader without fibers, what is sass-loader's dependecy?

**Comment by Morgul** [comment]
The problem I keep running into is that, under node v16 and npm v8.1.2, `fibers` is installed by default, and there's no way I can find to block it. It should be removed from peer dependencies, and made an optional dependency, or simply removed, as the original author doesn't recommend its use anymore.

**Comment by alexander-akait** [comment]
@Morgul Yes, you are right, feel free to send a PR

**Comment by alexander-akait** [comment]
It should be not in `peerDependencies`, looks like it was done by mistake

**Comment by alexander-akait** [comment]
Same for `node-sass`

**Comment by Morgul** [comment]
@alexander-akait To be clear, are you looking for a PR to remove fibers, or make it an optional dependency?

I just re-read the section on optional dependencies, and, as I read it, it will still install automatically.

Either way, I'm happy to put in a PR. 😄

**Comment by alexander-akait** [comment]
We need remove it from `peerDependencies`, it is already optional https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L54, so yarn will work, same for `node-sass`, npm v8 by default install peer deps, so now we install very many unnecessary deps

**Comment by alexander-akait** [comment]
@Morgul I was wrong, there is RFC https://github.com/npm/rfcs/blob/main/implemented/0030-no-install-optional-peer-deps.md, npm/yarn/etc should not install peer deps as marker `optional`, so please check your package manager version, because we have https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L46

**Comment by Morgul** [comment]
@alexander-akait I have npm v8.3.0 (which is the latest) and it still installs fibers. While that RFC is in 'implemented', I can't figure out which version of NPM it should be in.

It sure doesn't seem like this is working the way it's intended.

**Comment by alexander-akait** [comment]
Can you run `npm ls fibers`?

**Comment by Morgul** [comment]
Sure:

```PS C:\Users\morgul\devel\report-service> npm ls fibers
report-service@1.0.0 C:\Users\morgul\devel\report-service
+-- @nuxt/types@2.15.8
| `-- sass-loader@10.1.1
|   `-- fibers@5.0.0 deduped
`-- sass-loader@10.2.0
  `-- fibers@5.0.0
```

**Comment by alexander-akait** [comment]
`nuxt/types` install them for types

**Comment by daan33** [comment]
Any updates here?  I'm running into the same problem.  I don't have `@nuxt/types` but it is listed under `sass-loader@10.2.0` as `fibers@5.0.0`.  I'm using the latest Nuxt 2 version.

**Comment by alexander-akait** [comment]
I don't mean to be rude, but what do you expect here with `Any updates here?`? Please open an issue in `nuxt` and ask them do not install outdated types

**Comment by Morgul** [comment]
I'm not sure what a good solution here is. Nuxt 2 uses webpack 4, not 5, which means that it's stuck on `sass-loader` 10.X, which is before https://github.com/webpack-contrib/sass-loader/commit/4ca004b9e733bd2261ec68a7db4de07d79cf331a, which should fix this issue. (The peers deps was a red herring, since it doesn't actually matter if `fibers` is installed, as long as it's not used by `sass-loader` on node 16.)

The new nuxt 3 uses webpack 5 and the latest `sass-loader`, but is a pre-release version and has some rather large breaking changes; upgrading to it isn't viable for me, at least, for a while yet.

The only 'fix' I can imagine, is backporting that change to the 10.x line and releasing a new 10.X version.

**Comment by alexander-akait** [comment]
Yes, if you send a PR I will merge and do release, sorry, a lot of tasks and do not have enough time to backport

**Comment by Morgul** [comment]
@alexander-akait No worries, this is something only affecting a few people, and I understand completely not focusing on it. 🙂

I'll try to get to backporting that this week, and put in a PR. Should I use the v10 branch? Or should I branch from whatever the latest released 10.X tag is?

**Comment by alexander-akait** [comment]
Yep, we should use https://github.com/webpack-contrib/sass-loader/tree/v10.2.0 as base, just backport the same

**Comment by Morgul** [comment]
@daan33 Try the latest `v10.2.1`, as that has the backported changes, and seems to work for me, now.

**Comment by daan33** [comment]
Works like a charm!  @Morgul Thanks so much and I apologize to @alexander-akait if I came off rude -- not my intention at all, you guys rock!
